In [1]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[9,8,7], [6,5,4], [3,2,1]])
res = a+b
print(res)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [2]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
result = [[0,0,0], [0,0,0], [0,0,0]]

print("matrix 1 is:")
for col_1 in a:
    print(col_1)

print("matrix 2 is:")
for col_2 in b:
    print(col_2)

print("The sum is:")
for i in range(len(a)):
    for j in range(len(a[0])):
        result[i][j] = a[i][j] + b[i][j]

for col_3 in result:
    print(col_3)

matrix 1 is:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
matrix 2 is:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]
The sum is:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]
